[package]
name = "set3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
mersenne64 = []

[dependencies]
aes = "0.8.2"
getrandom = "0.2"
set1 = {path = "../set1"}
set2 = {path = "../set2"}
